Npaez
openshift/managed-scripts pull request #136
Opened 2023-09-15 15:06 UTC by NelsonLomboPaez

This is a script to delete a worker node when it's stuck and when we don't have time to investigate because it's causing some disruption on the customer side or because the customer does not need an RCA and just wants to have the node recreated. I have followed the steps from the SOAP[0]. I tried to not overcomplicate the code since it's my first one but I'm more than happy to adjust any changes that might be needed. I'll follow up on the PR but if someone wants to ping me, feel free to do it in Slack (@npaez)

I was thinking of adding a drain function before deleting the machine but the API is going to do that so I didn't want to duplicate work there. It might be interesting to add a PDB check on the node before deleting it(I can create another managed script that checks just that in a particular node) and we will require customer approval to run this script.

If something is not clear in the code itself or in the Readme, let me know.

Thank you!

**
[0] https://github.com/openshift/ops-sop/blob/ce50d672e5d83fd6f7318228116660854d6d8905/v4/howto/node.md#replace-infra-or-worker-node

2023-09-18 06:02 UTC, feichashao commented
We can also add another check:
- Ensure the machine is managed by a machineset. In normal case all machines are managed by a machineset, but in case something out of expectation.
- If there are other machines already in `Deleting`, it should stop and request manual investigation before process. In such case, likely something wrong will prevent the machine from deleting (eg aws permission issue, PDB).

2023-09-27 07:18 UTC, MitaliBhalla requested changes

2023-09-27 07:18 UTC, MitaliBhalla commented on scripts/CEE/delete-worker-node/README.md
> +
```suggestion
```

2023-09-27 07:18 UTC, MitaliBhalla commented on scripts/CEE/delete-worker-node/README.md
> +
```suggestion
```

2023-09-27 07:18 UTC, MitaliBhalla commented on scripts/CEE/delete-worker-node/README.md
> +
```suggestion
```

2023-09-27 07:18 UTC, MitaliBhalla commented on scripts/CEE/delete-worker-node/README.md
> +
```suggestion
```

2023-09-27 07:18 UTC, MitaliBhalla commented on scripts/CEE/delete-worker-node/README.md
> +
```suggestion
```

2023-09-27 07:19 UTC, MitaliBhalla commented
/retest

2023-09-27 07:22 UTC, MitaliBhalla requested changes

2023-12-11 01:41 UTC, feichashao commented on scripts/CEE/delete-worker-node/metadata.yaml
> +        - machines
```suggestion
  clusterRoleRules:
    - verbs:
        - get
        - list
      apiGroups:
        - ''
      resources:
        - nodes
  roles:
    - namespace: "openshift-machine-api"
       rules:
          - verbs:
            - get
            - list
            - delete
            apiGroups:
            - "machin.openshift.io"
            resources:
            - "machines"
```

The `machine` resource is namespaced, we can scope it to `openshift-machine-api`.

2023-12-11 01:44 UTC, feichashao commented
@NelsonLomboPaez  Thanks for following up!  The script looks good to me in general.  I added some change requests, please take a look when you have time.

Also suggest to edit the title of this pull request to summarize what this pull request does, eg `Add a script to delete a machine`.

2023-12-11 07:48 UTC, feichashao commented on scripts/CEE/delete-worker-node/metadata.yaml
> +            - "machines"
```suggestion
      rules:
        - verbs:
            - get
            - list
            - delete
          apiGroups:
            - "machine.openshift.io"
          resources:
            - "machines"
```

2023-12-11 16:14 UTC, NelsonLomboPaez commented
This is the list of the nodes in the cluster:

~~~
$ oc get nodes
NAME                                        STATUS   ROLES                  AGE   VERSION
ip-10-0-2-236.eu-west-1.compute.internal    Ready    control-plane,master   20h   v1.27.6+d548052
ip-10-0-24-212.eu-west-1.compute.internal   Ready    control-plane,master   20h   v1.27.6+d548052
ip-10-0-33-121.eu-west-1.compute.internal   Ready    worker                 20h   v1.27.6+d548052
ip-10-0-38-113.eu-west-1.compute.internal   Ready    infra,worker           19h   v1.27.6+d548052
ip-10-0-38-17.eu-west-1.compute.internal    Ready    infra,worker           19h   v1.27.6+d548052
ip-10-0-55-218.eu-west-1.compute.internal   Ready    control-plane,master   20h   v1.27.6+d548052
ip-10-0-6-132.eu-west-1.compute.internal    Ready    worker                 17m   v1.27.6+d548052

~~~

And this is the list of machines:

~~~
$ oc get machines -n openshift-machine-api
NAME                                    PHASE     TYPE         REGION      ZONE         AGE
npaezms-vlww7-infra-eu-west-1a-6mmx4    Running   r5.xlarge    eu-west-1   eu-west-1a   20h
npaezms-vlww7-infra-eu-west-1a-hrmd6    Running   r5.xlarge    eu-west-1   eu-west-1a   20h
npaezms-vlww7-master-0                  Running   m5.2xlarge   eu-west-1   eu-west-1a   20h
npaezms-vlww7-master-1                  Running   m5.2xlarge   eu-west-1   eu-west-1a   20h
npaezms-vlww7-master-2                  Running   m5.2xlarge   eu-west-1   eu-west-1a   20h
npaezms-vlww7-worker-eu-west-1a-87d7s   Running   m5.xlarge    eu-west-1   eu-west-1a   22m
npaezms-vlww7-worker-eu-west-1a-dgl99   Running   m5.xlarge    eu-west-1   eu-west-1a   20h

~~~

List of machines associated to nodes:

~~~
$ oc get nodes --output="custom-columns=NODE NAME:.metadata.name,MACHINE NAME:.metadata.annotations.machine\.openshift\.io/machine"
NODE NAME                                   MACHINE NAME
NODE NAME                                   MACHINE NAME
ip-10-0-2-236.eu-west-1.compute.internal    openshift-machine-api/npaezms-vlww7-master-1
ip-10-0-24-212.eu-west-1.compute.internal   openshift-machine-api/npaezms-vlww7-master-2
ip-10-0-33-121.eu-west-1.compute.internal   openshift-machine-api/npaezms-vlww7-worker-eu-west-1a-dgl99
ip-10-0-38-113.eu-west-1.compute.internal   openshift-machine-api/npaezms-vlww7-infra-eu-west-1a-6mmx4
ip-10-0-38-17.eu-west-1.compute.internal    openshift-machine-api/npaezms-vlww7-infra-eu-west-1a-hrmd6
ip-10-0-55-218.eu-west-1.compute.internal   openshift-machine-api/npaezms-vlww7-master-0
ip-10-0-6-132.eu-west-1.compute.internal    openshift-machine-api/npaezms-vlww7-worker-eu-west-1a-87d7s


~~~

I have run some tests to verify that the script is working correctly, the test and the output are described in the following lines.

1- Test by removing a node that is not present on the cluster:

~~~
$ ocm backplane testjob create -l delete-worker-node/ -p NODE="non-exist" -p MACHINE="npaez-ms-59xbk-worker-eu-west-1a-lm6"

	Test job openshift-job-dev-p86kw created successfully
	
	Run "ocm backplane testjob get openshift-job-dev-p86kw" for details
	Run "ocm backplane testjob logs openshift-job-dev-p86kw" for job logs
	
TestId: openshift-job-dev-p86kw
[nelsonpaez@fedora delete-worker-node]$ ocm backplane testjob logs openshift-job-dev-p86kw
Verifying that the "non-exist" is not a master nor a infra node...
[Error] "non-exist" is a master or a infra node or the node it's not present so it cannot be deleted. Exiting script
~~~

2- Test by removing a node that exist but with an incorrect machine name:

~~~
$ ocm backplane testjob create -l delete-worker-node/ -p NODE="ip-10-0-33-121.eu-west-1.compute.internal" -p MACHINE="not-present"

	Test job openshift-job-dev-p4fdn created successfully
	
	Run "ocm backplane testjob get openshift-job-dev-p4fdn" for details
	Run "ocm backplane testjob logs openshift-job-dev-p4fdn" for job logs
	
TestId: openshift-job-dev-p4fdn
[nelsonpaez@fedora delete-worker-node]$ ocm backplane testjob logs openshift-job-dev-p4fdn
Verifying that the "ip-10-0-33-121.eu-west-1.compute.internal" is not a master nor a infra node...
[OK] "ip-10-0-33-121.eu-west-1.compute.internal" is not a master nor a infra node. Proceeding with next check
Checking if the "not-present" is a machine present on the cluster...
[Error] "not-present" is not present on the cluster. Exiting script

~~~

3-Trying to remove a master node:

~~~
$ ocm backplane testjob create -l delete-worker-node/ -p NODE="ip-10-0-2-236.eu-west-1.compute.internal" -p MACHINE="npaezms-vlww7-master-2"

	Test job openshift-job-dev-b26cb created successfully
	
	Run "ocm backplane testjob get openshift-job-dev-b26cb" for details
	Run "ocm backplane testjob logs openshift-job-dev-b26cb" for job logs
	
TestId: openshift-job-dev-b26cb
[nelsonpaez@fedora delete-worker-node]$ ocm backplane testjob logs openshift-job-dev-b26cb
Verifying that the "ip-10-0-2-236.eu-west-1.compute.internal" is not a master nor a infra node...
[Error] "ip-10-0-2-236.eu-west-1.compute.internal" is a master or a infra node or the node it's not present so it cannot be deleted. Exiting script
~~~

Trying to delete an infra node:

~~~
$ ocm backplane testjob create -l delete-worker-node/ -p NODE="ip-10-0-38-113.eu-west-1.compute.internal" -p MACHINE="npaezms-vlww7-master-2"

	Test job openshift-job-dev-vvjrs created successfully
	
	Run "ocm backplane testjob get openshift-job-dev-vvjrs" for details
	Run "ocm backplane testjob logs openshift-job-dev-vvjrs" for job logs
	
TestId: openshift-job-dev-vvjrs
[nelsonpaez@fedora delete-worker-node]$ ocm backplane testjob logs openshift-job-dev-vvjrs
Verifying that the "ip-10-0-38-113.eu-west-1.compute.internal" is not a master nor a infra node...
[Error] "ip-10-0-38-113.eu-west-1.compute.internal" is a master or a infra node or the node it's not present so it cannot be deleted. Exiting script

~~~


Trying to delete a machine associated with a different node:

~~~
$ ocm backplane testjob create -l delete-worker-node/ -p NODE="ip-10-0-33-121.eu-west-1.compute.internal" -p MACHINE="npaezms-vlww7-worker-eu-west-1a-87d7s"

	Test job openshift-job-dev-k57q4 created successfully
	
	Run "ocm backplane testjob get openshift-job-dev-k57q4" for details
	Run "ocm backplane testjob logs openshift-job-dev-k57q4" for job logs
	
TestId: openshift-job-dev-k57q4
[nelsonpaez@fedora delete-worker-node]$ ocm backplane testjob logs openshift-job-dev-k57q4
Verifying that the "ip-10-0-33-121.eu-west-1.compute.internal" is not a master nor a infra node...
[OK] "ip-10-0-33-121.eu-west-1.compute.internal" is not a master nor a infra node. Proceeding with next check
Checking if the "npaezms-vlww7-worker-eu-west-1a-87d7s" is a machine present on the cluster...
[OK] "npaezms-vlww7-worker-eu-west-1a-87d7s" is present on the cluster. Proceeding with next check
Checking if the "npaezms-vlww7-worker-eu-west-1a-87d7s" is the machine associated to the correct node...
[Error] "npaezms-vlww7-worker-eu-west-1a-87d7s" is not correct, please, check that you have provided the correct values. Exiting script

~~~

For the last test, I have added a new node via the OCM so we have a `Machine` in `provisioning` state so the script should fail since not all the `Machine` are in `Running`, in this case the node exist and the machine is the one associated to that node:

~~~
$ oc get machines -A
NAMESPACE               NAME                                    PHASE          TYPE         REGION      ZONE         AGE
openshift-machine-api   npaezms-vlww7-infra-eu-west-1a-6mmx4    Running        r5.xlarge    eu-west-1   eu-west-1a   20h
openshift-machine-api   npaezms-vlww7-infra-eu-west-1a-hrmd6    Running        r5.xlarge    eu-west-1   eu-west-1a   20h
openshift-machine-api   npaezms-vlww7-master-0                  Running        m5.2xlarge   eu-west-1   eu-west-1a   20h
openshift-machine-api   npaezms-vlww7-master-1                  Running        m5.2xlarge   eu-west-1   eu-west-1a   20h
openshift-machine-api   npaezms-vlww7 [...]

2023-12-13 06:03 UTC, feichashao commented on template/metadata.json
> +{"file": "script.sh", "name": "template", "description": "A template for managed scripts which lists master machines of the logged in cluster.", "author": "supreeth7", "allowedGroups": ["SREP"], "rba
This file is not needed as it is a temp file for validation, could you help to remove it?

2023-12-13 06:11 UTC, feichashao commented
/label tide/merge-method-squash

2023-12-14 05:07 UTC, feichashao commented
/lgtm
/approve

2023-12-14 05:20 UTC, merged