Add pull request template for managedscript
openshift/managed-scripts pull request #154
Opened 2023-11-23 08:35 UTC by Dee-6777

Adding a template that will help add convey more information about the pr

2023-11-23 12:14 UTC, supreeth7 requested changes

2023-11-23 12:14 UTC, supreeth7 commented on PULL_REQUEST_TEMPLATE.md
The directory structure isn't correct here, GitHub expects all workflow related files to be present under the `.github` folder, so the right filepath would be `.github/PULL_REQUEST_TEMPLATE.md`.

2023-11-23 18:59 UTC, Dee-6777 commented on PULL_REQUEST_TEMPLATE.md
Thanks! I thought using` PULL_REQUEST_TEMPLATE.md` would work

2023-11-27 06:43 UTC, bmeng commented
/lgtm
/approve

2023-11-27 06:51 UTC, merged