add :Z mount to fix local validation errors when using podman
openshift/managed-scripts pull request #193
Opened 2024-06-12 11:31 UTC by RaphaelBut

not sure if this is the right approach but when calling `make validation ` using podman I get permissions errors.

2024-06-12 11:32 UTC, RaphaelBut commented
I have not tested that this still works with docker

2024-06-20 06:12 UTC, Tessg22 requested changes

2024-06-20 06:12 UTC, Tessg22 commented on hack/schema_validation.sh
Shouldn't we add error handling to capture potential errors during execution?
```
  # Ensure the function receives the required parameter
  if [ -z "$1" ]; then
    echo "Error: No YAML files specified."
    return 1
  fi

  local yaml_files="$1"
```

2024-08-07 06:46 UTC, bmeng commented
Hi @RaphaelBut any update for this PR? Is it still needed?

2024-09-03 02:28 UTC, xiaoyu74 commented
@RaphaelBut - Please rebase the PR to resolve the conflicts. Also, any updates for the PR based on the current review feedback?

2025-02-01 08:00 UTC, closed without merging