OSD-12042 add a script to replace master
openshift/managed-scripts pull request #86
Opened 2022-09-15 09:20 UTC by feichashao

Add a script to help replacing the master machine. Input the machine name of the master, and it will delete that master machine and create a new one with same configuration.

2022-09-15 15:27 UTC, supreeth7 requested changes
Thank you for working on this, this script would be super helpful! 
Took a quick pass through the code, didn't get a chance to test it though, found a few nits.

Suggestion: I've noticed `validate_input()` doing a lot more than what its name suggests, perhaps we can fragment the code to an extent for better readability. I would prefer breaking it down into additional modular functions like `checkClusterVersion()`,`isUpgrading()`,`validateMachine()`,`checkMastersHealth()`,`checkETCDHealth()`. Modularity for the win 🏆

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +echo "INFO: wait for the original master gone"
```suggestion
echo "INFO: waiting for the original master to be deleted..."
```

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +ORIGN_MASTER_JSON=$(oc -n "$MACHINE_NS" get machine "$machine" -o json)
```suggestion
OLD_MASTER_JSON=$(oc -n "$MACHINE_NS" get machine "$machine" -o json)
```

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +    echo "ERROR: The living master nodes not equal 2 after deleting $machine"
```suggestion
    echo "ERROR: Current master nodes are not equal to 2 after deleting $machine"
```

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +echo "INFO: wait for the new master become ready"
```suggestion
echo "INFO: waiting for the new master to become ready..."
```

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +    echo "ERROR: Ready master nodes not equal 3"
```suggestion
    echo "ERROR: Master nodes with the state 'Ready' are not equal to 3"
```

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +    echo "ERROR: There are more than 1 etcd members have no corresponding running masters, need human investigation"
```suggestion
    echo "ERROR: There are more than 1 etcd members having no corresponding running masters, further human investigation needed"
```

2022-09-15 15:27 UTC, supreeth7 commented on scripts/SREP/replace-master/script.sh
> +    echo "ETCD has 3 healthy members, master replacement succeed"
```suggestion
    echo "ETCD has 3 healthy members, master replacement successful!"
```

2022-09-16 04:14 UTC, feichashao commented
@supreeth7  Thank you very much for reviewing and providing suggestions!  I changed the script to follow the coding style and put the checks to `preflight_check()`.  I didn't further modulized that because each check is a few lines of code and need to reuse some info from the previous check, putting them into dedicated functions will become another wrapper of the oc command and need passing info around. That's said, I am still a fan of modularity :D

2022-09-16 07:07 UTC, supreeth7 commented
Thanks @feichashao, looks great! 
Happy to merge once confirmed this has been tested in stage.

2022-09-16 07:08 UTC, MitaliBhalla commented
> Thanks @feichashao, looks great! Happy to merge once confirmed this has been tested in stage.

I have tested this on stage for 4.8,4.9 and 4.10 clusters. Good to go from my side.

2022-09-16 07:11 UTC, supreeth7 commented
/lgtm

2022-09-16 07:12 UTC, supreeth7 commented
/label tide/merge-method-squash

2022-09-16 07:17 UTC, merged